language: minimal
branches:
  only:
    - master # build master branch only
script:
  - ./updater.sh
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: iana_service_catalog.gz
  skip_cleanup: true
  overwrite: true
